[package]
name = "async-hwi"
version = "0.0.10"
edition = "2018"
description = "Async hardware wallet interface"
authors = ["Edouard Paris <m@edouard.paris>"]
license-file = "LICENSE"
repository = "https://github.com/revault/async-hwi"
keywords = ["bitcoin"]

[features]
default = ["ledger", "specter", "bitbox"]
bitbox = ["tokio", "hidapi", "bitbox-api"]
specter = ["tokio", "tokio-serial", "serialport"]
ledger = ["regex", "tokio", "ledger_bitcoin_client", "ledger-transport-hid", "ledger-apdu", "hidapi"]

[dependencies]
base64 = "0.13.0"
async-trait = "0.1.52"
futures = "0.3"
bitcoin = { version = "0.30.0", default-features = false, features = ["base64", "serde", "no-std"] }

# specter & ledger
tokio = { version = "1.21.0", features = ["net", "time", "io-util", "sync"], optional = true }

# specter
tokio-serial = { version = "5.4.1", optional = true }
serialport = { version = "4.2", optional = true }

#bitbox
bitbox-api = { git = "https://github.com/edouardparis/bitbox-api-rs", branch = "add-transport-implementing-Send-to-usb", features = ["usb", "tokio", "enforce-send"], optional = true }

#bitbox & ledger
hidapi = { version = "2.4.1", features = ["linux-static-hidraw"], default-features = false, optional = true }

# ledger
regex = { version = "1.6.0", optional = true }
ledger_bitcoin_client = { version = "0.3.2", optional = true }
ledger-apdu = { version = "0.10", optional = true }
ledger-transport-hid = { git = "https://github.com/edouardparis/ledger-rs", branch = "hidapi-2.4.1", optional = true }

[dev-dependencies]
tokio = { version = "1.21", features = ["macros", "net", "rt", "rt-multi-thread", "io-util", "sync"] }
