[package]
name = "async-hwi-cli"
version = "0.0.1"
edition = "2021"
description = "CLI to communicate with Hardware Wallet Interface"
authors = ["Edouard Paris <m@edouard.paris>"]
license-file = "../LICENSE"
repository = "https://github.com/wizardsardine/async-hwi"
keywords = ["bitcoin", "hwi"]

[[bin]]
name = "hwi"
path = "src/bin/hwi.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
bitcoin = "0.30.0"
hex = "0.4"
async-hwi = { path = ".." }
tokio = { version = "1", features = ["macros", "net", "rt", "rt-multi-thread", "io-util", "sync"] }
